// packages/create-farm-app/templates/_renderers/solid/src/app/layout.tsx
import type { LayoutProps, Metadata } from "@farm.js/core";
import "./globals.css";
import "./solid.css";

export const metadata: Metadata = {
  title: "FARMJS Solid App",
  description: "A framework for product-integrated apps",
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml", sizes: "any" }],
  },
};

export default function RootLayout(props: LayoutProps) {
  return <>{props.children}</>;
}

// packages/create-farm-app/templates/_renderers/vue/src/app/layout.vue
<script lang="ts">
import type { Metadata } from "@farm.js/core";
import "./globals.css";
import "./vue.css";

export const metadata: Metadata = {
  title: "FARMJS Vue App",
  description: "A framework for product-integrated apps",
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml", sizes: "any" }],
  },
};
</script>

<script setup lang="ts">
defineOptions({ inheritAttrs: false });
</script>

<template>
  <slot />
</template>
