// benchmarks/frameworks/apps/sveltekit/src/routes/+page.svelte
<script module lang="ts">
  const items = Array.from({ length: 120 }, (_, index) => ({
    id: index + 1,
    label: `Benchmark item ${String(index + 1).padStart(3, "0")}`,
  }));
</script>

<script lang="ts">
  let { data } = $props();
</script>

<main
  data-benchmark-marker="framework-benchmark-v1"
  data-item-count={items.length}
  data-rendered-at={data.renderedAt}
>
  <header>
    <p>Dynamic SSR fixture</p>
    <h1>Framework benchmark fixture</h1>
    <time datetime={new Date(data.renderedAt).toISOString()}>{data.renderedAt}</time>
  </header>
  <ul>
    {#each items as item (item.id)}
      <li><span>{item.id}</span><strong>{item.label}</strong></li>
    {/each}
  </ul>
</main>

// benchmarks/frameworks/apps/tanstack/src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router";

const items = Array.from({ length: 120 }, (_, index) => ({
  id: index + 1,
  label: `Benchmark item ${String(index + 1).padStart(3, "0")}`,
}));

export const Route = createFileRoute("/")({
  component: BenchmarkPage,
  loader: () => ({ renderedAt: Date.now() }),
});

function BenchmarkPage() {
  const { renderedAt } = Route.useLoaderData();

  return (
    <main
      data-benchmark-marker="framework-benchmark-v1"
      data-item-count={items.length}
      data-rendered-at={renderedAt}
    >
      <header>
        <p>Dynamic SSR fixture</p>
        <h1>Framework benchmark fixture</h1>
        <time dateTime={new Date(renderedAt).toISOString()}>{renderedAt}</time>
      </header>
      <ul>
        {items.map((item) => (
          <li key={item.id}>
            <span>{item.id}</span>
            <strong>{item.label}</strong>
          </li>
        ))}
      </ul>
    </main>
  );
}
