// examples/vue-renderer/src/app/page.vue
<script lang="ts">
export const hydrate = true;
</script>

<script setup lang="ts">
import GreetingPanel from "../features/greeting/greeting-panel.vue";
import ResourceLinks from "../components/resource-links.vue";

defineOptions({ inheritAttrs: false });
</script>

<template>
  <main class="page-shell">
    <section class="hero">
      <div class="eyebrow">
        <span>00</span>
        <span>FARMJS / Vue renderer</span>
      </div>

      <h1>Vue UI. <span>FARMJS server.</span></h1>

      <GreetingPanel />
      <ResourceLinks class="links" />
    </section>
  </main>
</template>

// examples/svelte-renderer/src/app/page.svelte
<script module lang="ts">
  export const hydrate = true;
</script>

<script lang="ts">
  import ResourceLinks from "../components/resource-links.svelte";
  import GreetingPanel from "../features/greeting/greeting-panel.svelte";
</script>

<main class="page-shell">
  <section class="hero">
    <div class="eyebrow">
      <span>00</span>
      <span>FARMJS / Svelte renderer</span>
    </div>

    <h1>Svelte UI. <span>FARMJS server.</span></h1>

    <GreetingPanel />
    <ResourceLinks class="links" />
  </section>
</main>
