// packages/create-farm-app/templates/_renderers/svelte/src/app/layout.svelte
<script module lang="ts">
  import type { Metadata } from "@farm.js/core";
  import "./globals.css";
  import "./svelte.css";

  export const metadata: Metadata = {
    title: "FARMJS Svelte App",
    description: "A framework for product-integrated apps",
    icons: {
      icon: [{ url: "/favicon.svg", type: "image/svg+xml", sizes: "any" }],
    },
  };
</script>

<script lang="ts">
  import type { Snippet } from "svelte";

  let { children }: { children?: Snippet } = $props();
</script>

{@render children?.()}

// packages/create-farm-app/templates/_renderers/solid/src/app/layout.tsx
import type { LayoutProps, Metadata } from "@farm.js/core";
import "./globals.css";
import "./solid.css";

export const metadata: Metadata = {
  title: "FARMJS Solid App",
  description: "A framework for product-integrated apps",
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml", sizes: "any" }],
  },
};

export default function RootLayout(props: LayoutProps) {
  return <>{props.children}</>;
}
