// examples/solid-renderer/src/features/greeting/greeting-panel.tsx
"use client";

import { createSignal } from "solid-js";
import { apiClient } from "./api";

export function GreetingPanel() {
  const [message, setMessage] = createSignal("Ready for a typed server call.");
  const [detail, setDetail] = createSignal(
    "createServerFn is waiting on the server",
  );
  const [pending, setPending] = createSignal(false);

  const callServer = async () => {
    setPending(true);

    try {
      const result = await apiClient.greeting.post({
        body: { name: "Solid" },
      });

      if (result.error) throw result.error;
      if (!result.data) throw new Error("The server returned no greeting");

      setMessage(result.data.message);
      setDetail(
        `server invocation ${result.data.invocation} / ${result.data.runtime}`,
      );
    } catch (error) {
      setMessage(
        error instanceof Error ? error.message : "The server call failed",
      );
      setDetail("request failed");
    } finally {
      setPending(false);
    }
  };

  return (
    <div class="server-demo">
      <div class="demo-row">
        <span>01</span>
        <code>renderer: solid()</code>
      </div>
      <div class="demo-row">
        <span>02</span>
        <button type="button" onClick={callServer} disabled={pending()}>
          {pending() ? "Calling server…" : message()}
        </button>
      </div>
      <div class="demo-row demo-detail" aria-live="polite">
        <span>03</span>
        <code>{detail()}</code>
      </div>
    </div>
  );
}

// examples/preact-renderer/src/features/greeting/greeting-panel.tsx
"use client";

import { useState } from "preact/hooks";
import { apiClient } from "./api";

export function GreetingPanel() {
  const [message, setMessage] = useState("Ready for a typed server call.");
  const [detail, setDetail] = useState("createServerFn is waiting on the server");
  const [pending, setPending] = useState(false);
  const [failed, setFailed] = useState(false);

  const callServer = async () => {
    setPending(true);
    setFailed(false);

    try {
      const result = await apiClient.greeting.post({
        body: { name: "Preact" },
      });

      if (result.error) throw result.error;
      if (!result.data) throw new Error("The server returned no greeting");

      setMessage(result.data.message);
      setDetail(`server invocation ${result.data.invocation} / ${result.data.runtime}`);
    } catch (error) {
      setFailed(true);
      setMessage(error instanceof Error ? error.message : "The server call failed");
      setDetail("request failed / try again");
    } finally {
      setPending(false);
    }
  };

  return (
    <div className="server-demo">
      <div className="demo-row">
        <span>01</span>
        <code>renderer: preact()</code>
      </div>
      <div className="demo-row">
        <span>02</span>
        <button
          type="button"
          className={failed ? "failed" : undefined}
          onClick={callServer}
          disabled={pending}
        >
          {pending ? "Calling server…" : message}
        </button>
      </div>
      <div className="demo-row demo-detail" aria-live="polite">
        <span>03</span>
        <code>{detail}</code>
      </div>
    </div>
  );
}
