// packages/create-farm-app/templates/_integrations/better-auth/vue/src/components/auth-shell.vue
<script setup lang="ts">
import ResourceLinks from "./resource-links.vue";
</script>

<template>
  <main class="auth-shell">
    <a class="auth-home-link" href="/" aria-label="Back to starter home">
      <span>00</span>
      <span>FARMJS / Vue + Better Auth</span>
    </a>

    <section class="auth-form-side"><slot /></section>
    <ResourceLinks class="auth-resource-links" />
  </main>
</template>

// packages/create-farm-app/templates/_integrations/better-auth/preact/src/components/auth-shell.tsx
import type { ComponentChildren } from "preact";
import { ResourceLinks } from "./resource-links";

export function AuthShell({ children }: { children: ComponentChildren }) {
  return (
    <main className="auth-shell">
      <a className="auth-home-link" href="/" aria-label="Back to starter home">
        <span>00</span>
        <span>FARMJS / Preact + Better Auth</span>
      </a>

      <section className="auth-form-side">{children}</section>
      <ResourceLinks className="auth-resource-links" />
    </main>
  );
}
