// packages/create-farm-app/templates/_integrations/better-auth/vue/src/app/layout.vue
<script lang="ts">
import type { Metadata } from "@farm.js/core";
import "./globals.css";

export const metadata: Metadata = {
  title: "FARMJS Vue Better Auth Starter",
  description: "Better Auth with FARMJS and Vue",
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml", sizes: "any" }],
  },
};
</script>

<script setup lang="ts">
defineOptions({ inheritAttrs: false });
</script>

<template>
  <slot />
</template>

// packages/create-farm-app/templates/_integrations/better-auth/solid/src/app/layout.tsx
import type { LayoutProps, Metadata } from "@farm.js/core";
import "./globals.css";

export const metadata: Metadata = {
  title: "FARMJS Solid Better Auth Starter",
  description: "Better Auth with FARMJS and Solid",
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml", sizes: "any" }],
  },
};

export default function RootLayout(props: LayoutProps) {
  return <>{props.children}</>;
}
