// packages/create-farm-app/templates/_integrations/better-auth/preact/src/components/auth-shell.tsx
import type { ComponentChildren } from "preact";
import { ResourceLinks } from "./resource-links";

export function AuthShell({ children }: { children: ComponentChildren }) {
  return (
    <main className="auth-shell">
      <a className="auth-home-link" href="/" aria-label="Back to starter home">
        <span>00</span>
        <span>FARMJS / Preact + Better Auth</span>
      </a>

      <section className="auth-form-side">{children}</section>
      <ResourceLinks className="auth-resource-links" />
    </main>
  );
}

// packages/create-farm-app/templates/_integrations/better-auth/solid/src/components/auth-shell.tsx
import type { JSX } from "solid-js";
import { ResourceLinks } from "./resource-links";

export function AuthShell(props: { children: JSX.Element }) {
  return (
    <main class="auth-shell">
      <a class="auth-home-link" href="/" aria-label="Back to starter home">
        <span>00</span>
        <span>FARMJS / Solid + Better Auth</span>
      </a>

      <section class="auth-form-side">{props.children}</section>
      <ResourceLinks className="auth-resource-links" />
    </main>
  );
}
