// packages/create-farm-app/templates/_integrations/better-auth/svelte/src/components/auth-shell.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import ResourceLinks from "./resource-links.svelte";

  let { children }: { children?: Snippet } = $props();
</script>

<main class="auth-shell">
  <a class="auth-home-link" href="/" aria-label="Back to starter home">
    <span>00</span>
    <span>FARMJS / Svelte + Better Auth</span>
  </a>

  <section class="auth-form-side">{@render children?.()}</section>
  <ResourceLinks className="auth-resource-links" />
</main>

// packages/create-farm-app/templates/_integrations/better-auth/vue/src/components/auth-shell.vue
<script setup lang="ts">
import ResourceLinks from "./resource-links.vue";
</script>

<template>
  <main class="auth-shell">
    <a class="auth-home-link" href="/" aria-label="Back to starter home">
      <span>00</span>
      <span>FARMJS / Vue + Better Auth</span>
    </a>

    <section class="auth-form-side"><slot /></section>
    <ResourceLinks class="auth-resource-links" />
  </main>
</template>
